import { FoodCategory } from './types';

export const allFoods: FoodCategory[] = [
    {
        category: "Vegetables",
        color: "bg-green-100", textColor: "text-green-800", borderColor: "border-green-300",
        items: [
            { name: "ASPARAGUS", emoji: " " }, { name: "BUTTERNUT SQUASH", emoji: "🎃" }, { name: "CAULIFLOWER", emoji: "🥦" },
            { name: "SWEET POTATO", emoji: "🍠" }, { name: "POTATOES", emoji: "🥔" }, { name: "PARSNIPS", emoji: "🥕" },
            { name: "BELL PEPPERS", emoji: "🫑" }, { name: "BEETS", emoji: "💜" }, { name: "CHAYOTE SQUASH", emoji: "🍐" },
            { name: "PUMPKIN", emoji: "🎃" }, { name: "CARROTS", emoji: "🥕" }, { name: "ZUCCHINI", emoji: "🥒" },
            { name: "MUSHROOMS", emoji: "🍄" }, { name: "ONION", emoji: "🧅" }, { name: "BRUSSELS SPROUTS", emoji: "🥬" },
            { name: "CORN", emoji: "🌽" }, { name: "CUCUMBER", emoji: "🥒" }, { name: "CELERY", emoji: "🥬" },
            { name: "PEAS", emoji: "🫛" }, { name: "SNAP PEAS", emoji: "🫛" }, { name: "CILANTRO", emoji: "🌿" },
            { name: "EGGPLANT", emoji: "🍆" }, { name: "GARLIC", emoji: "🧄" }, { name: "PARSLEY", emoji: "🌿" },
            { name: "KALE", emoji: "🥬" }, { name: "ARTICHOKE", emoji: " artichoke " }, { name: "BROCCOLI", emoji: "🥦" }
        ]
    },
    {
        category: "Grains",
        color: "bg-yellow-100", textColor: "text-yellow-800", borderColor: "border-yellow-300",
        items: [
            { name: "KAMUT", emoji: "🌾" }, { name: "CEREALS", emoji: "🥣" }, { name: "MILLET", emoji: "🌾" },
            { name: "OATMEAL", emoji: "🥣" }, { name: "BUCKWHEAT", emoji: "🌾" }, { name: "WAFFLES", emoji: "🧇" },
            { name: "HEALTHY MUFFINS", emoji: "🧁" }, { name: "PASTA", emoji: "🍝" }, { name: "COUSCOUS", emoji: "🍚" },
            { name: "POLENTA", emoji: "🌽" }, { name: "CORNMEAL", emoji: "🌽" }, { name: "BREAD", emoji: "🍞" },
            { name: "GNOCCHI", emoji: "🥔" }, { name: "TORTILLA", emoji: "🌮" }, { name: "FARRO", emoji: "🌾" },
            { name: "BARLEY", emoji: "🌾" }, { name: "BULGUR", emoji: "🌾" }, { name: "BROWN RICE", emoji: "🍚" },
            { name: "QUINOA", emoji: "🍚" }, { name: "FREEKEH", emoji: "🌾" }
        ]
    },
    {
        category: "Fruits",
        color: "bg-pink-100", textColor: "text-pink-800", borderColor: "border-pink-300",
        items: [
            { name: "AVOCADO", emoji: "🥑" }, { name: "TOMATOES", emoji: "🍅" }, { name: "ORANGE", emoji: "🍊" },
            { name: "LEMON & LIME", emoji: "🍋" }, { name: "PAPAYA", emoji: "🥬" }, { name: "PINEAPPLE", emoji: "🍍" },
            { name: "KIWIFRUIT", emoji: "🥝" }, { name: "MANGO", emoji: "🥭" }, { name: "STARFRUIT", emoji: "⭐" },
            { name: "FIGS", emoji: "💜" }, { name: "BANANA", emoji: "🍌" }, { name: "COCONUT", emoji: "🥥" },
            { name: "WATERMELON", emoji: "🍉" }, { name: "HONEYDEW", emoji: "🍈" }, { name: "CANTALOUPE", emoji: "🍈" },
            { name: "APPLESAUCE", emoji: "🍎" }, { name: "RASPBERRIES", emoji: "🍓" }, { name: "BLUEBERRIES", emoji: "🫐" },
            { name: "STRAWBERRIES", emoji: "🍓" }, { name: "GRAPES", emoji: "🍇" }, { name: "PEACHES", emoji: "🍑" },
            { name: "PEARS", emoji: "🍐" }, { name: "APPLES", emoji: "🍎" }
        ]
    },
    {
        category: "Plant Protein",
        color: "bg-blue-100", textColor: "text-blue-800", borderColor: "border-blue-300",
        items: [
            { name: "TOFU", emoji: "⬜" }, { name: "EDAMAME", emoji: "🫛" }, { name: "PEANUTS", emoji: "🥜" },
            { name: "ALMONDS", emoji: "🌰" }, { name: "WHITE BEANS", emoji: "🫘" }, { name: "CHICKPEAS", emoji: "🫘" },
            { name: "BLACK BEANS", emoji: "🫘" }, { name: "KIDNEY BEANS", emoji: "🫘" },
            { name: "LENTILS", emoji: "🍚" }, { name: "ALMOND BUTTER", emoji: "🌰" }, { name: "PEANUT BUTTER", emoji: "🥜" }, { name: "SEEDS", emoji: "🌱" }
        ]
    },
    {
        category: "Meat",
        color: "bg-red-100", textColor: "text-red-800", borderColor: "border-red-300",
        items: [
            { name: "FISH", emoji: "🐟" }, { name: "TUNA", emoji: "🐟" }, { name: "SARDINES", emoji: "🐟" },
            { name: "SALMON", emoji: "🐟" }, { name: "SHRIMP", emoji: "🍤" }, { name: "BEEF, SLICED", emoji: "🥩" },
            { name: "BEEF, GROUND", emoji: "🍔" }, { name: "CHICKEN", emoji: "🍗" }, { name: "LAMB", emoji: "🐑" },
            { name: "TURKEY", emoji: "🦃" }, { name: "PORK", emoji: "🐖" }
        ]
    },
    {
        category: "Dairy & Eggs",
        color: "bg-purple-100", textColor: "text-purple-800", borderColor: "border-purple-300",
        items: [
            { name: "YOGURT", emoji: "🥣" }, { name: "EGGS", emoji: "🥚" }, { name: "MOZZARELLA", emoji: "🧀" },
            { name: "RICOTTA CHEESE", emoji: "🧀" }, { name: "COTTAGE CHEESE", emoji: "🧀" }
        ]
    },
    {
        category: "Other",
        color: "bg-gray-100", textColor: "text-gray-800", borderColor: "border-gray-300",
        items: [
            { name: "WATER", emoji: "💧" },
            { name: "SPICES & HERBS", emoji: "🌿" }
        ]
    }
];

export const flatFoodList = allFoods.flatMap(cat => cat.items.map(item => item.name));
export const totalFoodCount = flatFoodList.length;

export const foodGuideData: { [key: string]: { allergyRisk: string; chokingRisk: string; serve6to8: string; serve9to12: string; } } = {
    // Vegetables
    "ASPARAGUS": { allergyRisk: "Low", chokingRisk: "Low (when soft-cooked)", serve6to8: "<h4 class='font-semibold'>6-8 Months:</h4><p>Steam or roast whole asparagus spears until very tender. Offer the whole spear for baby to gnaw on. The fibrous end is tough to chew through, reducing risk.</p>", serve9to12: "<h4 class='font-semibold mt-4'>9-12 Months:</h4><p>Continue serving whole, soft-cooked spears. As pincer grasp develops, you can chop the soft-cooked tips and stems into small, bite-sized pieces.</p>" },
    "BUTTERNUT SQUASH": { allergyRisk: "Low", chokingRisk: "Low (when soft-cooked)", serve6to8: "<h4 class='font-semibold'>6-8 Months:</h4><p>Roast or steam until very soft. Serve in long, thick spears. You can also serve it mashed on a pre-loaded spoon.</p>", serve9to12: "<h4 class='font-semibold mt-4'>9-12 Months:</h4><p>Continue with soft spears or mashed squash. As pincer grasp improves, you can offer soft-cooked, bite-sized cubes.</p>" },
    "CAULIFLOWER": { allergyRisk: "Low", chokingRisk: "Low (when soft-cooked)", serve6to8: "<h4 class='font-semibold'>6-8 Months:</h4><p>Steam or roast large florets until very soft. The 'tree' shape makes a great handle for baby to hold.</p>", serve9to12: "<h4 class='font-semibold mt-4'>9-12 Months:</h4><p>Continue serving large, soft florets. You can also break or cut the soft-cooked florets into smaller, pea-sized pieces for pincer grasp practice.</p>" },
    "SWEET POTATO": { allergyRisk: "Low", chokingRisk: "Low (when soft-cooked)", serve6to8: "<h4 class='font-semibold'>6-8 Months:</h4><p>Sweet potato must be cooked until very soft (easily smushed between your fingers). Serve as a large, soft-cooked spear (width of 2 fingers) or mashed on a pre-loaded spoon.</p>", serve9to12: "<h4 class='font-semibold mt-4'>9-12 Months:</h4><p>Continue serving as soft spears or mashed. As pincer grasp develops, you can offer small, soft-cooked cubes for baby to practice picking up.</p>" },
    "POTATOES": { allergyRisk: "Low", chokingRisk: "Low (when soft-cooked)", serve6to8: "<h4 class='font-semibold'>6-8 Months:</h4><p>Cook until very soft by baking, boiling, or steaming. Serve in large wedges or spears. Mashed potatoes on a pre-loaded spoon is also great.</p>", serve9to12: "<h4 class='font-semibold mt-4'>9-12 Months:</h4><p>Continue offering soft-cooked wedges or mashed potatoes. You can also offer small, soft-cooked cubes for pincer grasp practice.</p>" },
    "PARSNIPS": { allergyRisk: "Low", chokingRisk: "High (when raw)", serve6to8: "<h4 class='font-semibold'>6-8 Months:</h4><p>Must be cooked until very soft. Serve in long, thick spears that have been roasted or steamed until tender.</p>", serve9to12: "<h4 class='font-semibold mt-4'>9-12 Months:</h4><p>Continue serving soft-cooked spears, or cut into small, soft-cooked pieces for pincer grasp practice.</p>" },
    "BELL PEPPERS": { allergyRisk: "Low", chokingRisk: "Medium (when raw)", serve6to8: "<h4 class='font-semibold'>6-8 Months:</h4><p>Serve cooked until soft. Offer a large, long strip (about the width of two fingers) of roasted or steamed bell pepper, with skin removed if you prefer.</p>", serve9to12: "<h4 class='font-semibold mt-4'>9-12 Months:</h4><p>Continue with soft-cooked strips. You can also finely dice soft-cooked bell pepper for baby to pick up.</p>" },
    "BEETS": { allergyRisk: "Low", chokingRisk: "Low (when soft-cooked)", serve6to8: "<h4 class='font-semibold'>6-8 Months:</h4><p>Cook beets (roast or boil) until very soft. Serve in large, soft wedges. Be prepared for colorful messes!</p>", serve9to12: "<h4 class='font-semibold mt-4'>9-12 Months:</h4><p>Continue with soft-cooked wedges, or offer small, soft-cooked cubes as pincer grasp develops.</p>" },
    "CHAYOTE SQUASH": { allergyRisk: "Low", chokingRisk: "Low (when soft-cooked)", serve6to8: "<h4 class='font-semibold'>6-8 Months:</h4><p>Peel, remove the seed, and cook until very soft. Serve in long, thick spears. It has a mild flavor and is great for early eaters.</p>", serve9to12: "<h4 class='font-semibold mt-4'>9-12 Months:</h4><p>Continue serving soft-cooked spears or offer small, soft-cooked cubes.</p>" },
    "PUMPKIN": { allergyRisk: "Low", chokingRisk: "Low (when soft-cooked)", serve6to8: "<h4 class='font-semibold'>6-8 Months:</h4><p>Roast or steam until very soft. Serve in long, thick spears or as a thick mash on a pre-loaded spoon.</p>", serve9to12: "<h4 class='font-semibold mt-4'>9-12 Months:</h4><p>Continue with soft spears or mashed pumpkin. You can also offer soft-cooked, bite-sized cubes.</p>" },
    "CARROTS": { allergyRisk: "Low", chokingRisk: "High (when raw or undercooked)", serve6to8: "<h4 class='font-semibold'>6-8 Months:</h4><p><strong>NEVER</strong> serve raw baby carrots or raw carrot sticks. They are a major choking hazard.</p><p class='mt-2'>Carrots must be cooked until <strong>very soft</strong> (you can easily smash it between your thumb and forefinger). Serve in long, 1-inch thick spears (about the size of an adult finger) that have been roasted or steamed until tender.</p>", serve9to12: "<h4 class='font-semibold mt-4'>9-12 Months:</h4><p>Continue serving soft-cooked spears, or offer in small, soft-cooked, pincer-sized pieces. You can also offer shredded raw carrot, as this is much safer than a raw stick, but supervision is key.</p>" },
    "ZUCCHINI": { allergyRisk: "Low", chokingRisk: "Low (when soft-cooked)", serve6to8: "<h4 class='font-semibold'>6-8 Months:</h4><p>Zucchini must be cooked until very soft. Serve as large, soft-cooked spears (width of 2 fingers) with the skin on (for better grip) or off. Roasting or steaming works well. Avoid raw zucchini.</p>", serve9to12: "<h4 class='font-semibold mt-4'>9-12 Months:</h4><p>Continue serving soft-cooked spears. As pincer grasp develops, you can offer small, soft-cooked cubes (skin on or off). Shredded zucchini (raw or cooked) can also be mixed into muffins, pancakes, or fritters.</p>" },
    "MUSHROOMS": { allergyRisk: "Low", chokingRisk: "Medium", serve6to8: "<h4 class='font-semibold'>6-8 Months:</h4><p>Cook mushrooms until soft and slippery texture is reduced. Offer a whole, large, soft-cooked button mushroom or a large portobello cap cut into strips.</p>", serve9to12: "<h4 class='font-semibold mt-4'>9-12 Months:</h4><p>Continue with large pieces, or you can thinly slice soft-cooked mushrooms for pincer practice.</p>" },
    "ONION": { allergyRisk: "Low", chokingRisk: "Low (when cooked)", serve6to8: "<h4 class='font-semibold'>6-8 Months:</h4><p>Onion is best served cooked as a flavoring in other dishes. You can offer a large, soft-cooked wedge from a stew or soup for baby to gnaw on.</p>", serve9to12: "<h4 class='font-semibold mt-4'>9-12 Months:</h4><p>Finely dice cooked onion and mix it into meatballs, sauces, or egg dishes.</p>" },
    "BRUSSELS SPROUTS": { allergyRisk: "Low", chokingRisk: "Medium", serve6to8: "<h4 class='font-semibold'>6-8 Months:</h4><p>Cook until very soft. The leaves can be pulled apart and served, or you can offer a whole, very soft-cooked sprout for baby to gnaw on.</p>", serve9to12: "<h4 class='font-semibold mt-4'>9-12 Months:</h4><p>Serve very soft-cooked sprouts, cut in half or quarters lengthwise, to reduce the round shape hazard.</p>" },
    "CORN": { allergyRisk: "Low", chokingRisk: "High (as loose kernels)", serve6to8: "<h4 class='font-semibold'>6-8 Months:</h4><p>The safest way to serve corn is on the cob. Cut a whole cob into thirds and offer a piece to your baby to gnaw on. Supervise closely. Avoid loose kernels.</p>", serve9to12: "<h4 class='font-semibold mt-4'>9-12 Months:</h4><p>Continue serving on the cob. As baby gets older and has more teeth, they may be able to handle individual kernels, but supervise very closely as they are a choking risk.</p>" },
    "CUCUMBER": { allergyRisk: "Low", chokingRisk: "Medium", serve6to8: "<h4 class='font-semibold'>6-8 Months:</h4><p>Serve a large spear of cucumber (about the width of two fingers), with some of the peel left on as a handle for better grip. Baby will mostly suck on it. Supervise closely.</p>", serve9to12: "<h4 class='font-semibold mt-4'>9-12 Months:</h4><p>You can offer very thinly sliced cucumber (like half-moons or paper-thin strips) for pincer practice. Avoid round 'coin' shapes.</p>" },
    "CELERY": { allergyRisk: "Low", chokingRisk: "High (stringy and hard)", serve6to8: "<h4 class='font-semibold'>6-8 Months:</h4><p>Avoid raw celery. You can use a large celery stick as a 'teether' for baby to gnaw on (they won't get much off), or you can cook it until very soft in a soup or stew and offer a large, soft piece.</p>", serve9to12: "<h4 class='font-semibold mt-4'>9-12 Months:</h4><p>Continue to cook celery until soft. You can finely dice the soft-cooked celery to add to other dishes.</p>" },
    "PEAS": { allergyRisk: "Low", chokingRisk: "High (when whole)", serve6to8: "<h4 class='font-semibold'>6-8 Months:</h4><p>Serve peas mashed on a pre-loaded spoon or flattened/smashed onto a tray for baby to rake up with their fingers.</p>", serve9to12: "<h4 class='font-semibold mt-4'>9-12 Months:</h4><p>Continue serving smashed peas. As pincer grasp becomes very proficient, you can start offering single, soft-cooked peas for them to pick up. Supervise closely.</p>" },
    "SNAP PEAS": { allergyRisk: "Low", chokingRisk: "High (stringy/tough pod)", serve6to8: "<h4 class='font-semibold'>6-8 Months:</h4><p>It is best to remove the peas from the pod. Serve the individual peas smashed, as you would with regular peas.</p>", serve9to12: "<h4 class='font-semibold mt-4'>9-12 Months:</h4><p>Continue to serve the inner peas, smashed or eventually whole (with supervision). The pods can be steamed until very soft and offered as a strip to gnaw on.</p>" },
    "CILANTRO": { allergyRisk: "Low", chokingRisk: "Low", serve6to8: "<h4 class='font-semibold'>6-8 Months:</h4><p>Finely chop and mix into other foods like yogurt, mashed avocado, or soft-cooked meatballs to introduce flavor.</p>", serve9to12: "<h4 class='font-semibold mt-4'>9-12 Months:</h4><p>Continue using as a flavor enhancer in various dishes.</p>" },
    "EGGPLANT": { allergyRisk: "Low (though a rare allergen)", chokingRisk: "Low (when soft-cooked)", serve6to8: "<h4 class='font-semibold'>6-8 Months:</h4><p>Serve eggplant cooked until completely soft and tender. Large, long spears (with skin removed) that are roasted or steamed are perfect. You can also serve it mashed or as part of a dip like baba ganoush (watch the salt!).</p>", serve9to12: "<h4 class='font-semibold mt-4'>9-12 Months:</h4><p>Continue serving soft-cooked spears or offer soft-cooked, pincer-sized cubes. Eggplant is great at soaking up flavors in stews or pasta sauces.</p>" },
    "GARLIC": { allergyRisk: "Low", chokingRisk: "Low", serve6to8: "<h4 class='font-semibold'>6-8 Months:</h4><p>Use roasted garlic or garlic powder to flavor other foods. You can spread a soft, roasted garlic clove onto a piece of toast.</p>", serve9to12: "<h4 class='font-semibold mt-4'>9-12 Months:</h4><p>Continue using to flavor a variety of dishes.</p>" },
    "PARSLEY": { allergyRisk: "Low", chokingRisk: "Low", serve6to8: "<h4 class='font-semibold'>6-8 Months:</h4><p>Finely chop and mix into foods like sauces, meatballs, or yogurt to introduce new flavors.</p>", serve9to12: "<h4 class='font-semibold mt-4'>9-12 Months:</h4><p>Continue using as a flavor enhancer.</p>" },
    "KALE": { allergyRisk: "Low", chokingRisk: "Medium (tough leaves)", serve6to8: "<h4 class='font-semibold'>6-8 Months:</h4><p>Kale needs to be de-stemmed and cooked until very soft. You can finely chop it and mix it into other foods like eggs or oatmeal. 'Kale chips' can dissolve in the mouth but supervise closely.</p>", serve9to12: "<h4 class='font-semibold mt-4'>9-12 Months:</h4><p>Continue serving finely chopped and cooked in other dishes. Avoid serving large pieces of tough, leafy greens.</p>" },
    "ARTICHOKE": { allergyRisk: "Low", chokingRisk: "Low", serve6to8: "<h4 class='font-semibold'>6-8 Months:</h4><p>Serve only the soft, cooked artichoke heart. Make sure it's cooked until very tender and offer it in a large piece for baby to hold and gnaw on.</p>", serve9to12: "<h4 class='font-semibold mt-4'>9-12 Months:</h4><p>Continue serving soft-cooked artichoke hearts, either in large pieces or chopped into smaller, bite-sized bits.</p>" },
    "BROCCOLI": { allergyRisk: "Low", chokingRisk: "Medium (when raw or hard)", serve6to8: "<h4 class='font-semibold'>6-8 Months:</h4><p>Broccoli must be steamed or roasted until the stem is very soft (easily smushed between your fingers). Serve a large floret with a long 'handle' of the stem for baby to hold.</p>", serve9to12: "<h4 class='font-semibold mt-4'>9-12 Months:</h4><p>Continue serving soft-cooked florets, or chop the florets into small, pincer-sized pieces (both stem and flower) once soft-cooked.</p>" },

    // Grains
    "KAMUT": { allergyRisk: "High (Wheat)", chokingRisk: "Low", serve6to8: "<h4 class='font-semibold'>6-8 Months:</h4><p>Serve cooked Kamut berries mixed into yogurt or mashed sweet potato. You can also use Kamut flour to make baby-friendly pancakes or muffins.</p>", serve9to12: "<h4 class='font-semibold mt-4'>9-12 Months:</h4><p>Continue serving cooked berries, or offer baby-friendly baked goods made with Kamut flour.</p>" },
    "CEREALS": { allergyRisk: "Medium (can contain Wheat, Oats, etc.)", chokingRisk: "Low", serve6to8: "<h4 class='font-semibold'>6-8 Months:</h4><p>Choose low-sugar, low-sodium O-shaped cereals. They dissolve easily and are great for pincer grasp practice once baby is ready. Initially, you can serve them softened in milk or yogurt.</p>", serve9to12: "<h4 class='font-semibold mt-4'>9-12 Months:</h4><p>Offer O-shaped cereals dry on their tray for pincer grasp practice.</p>" },
    "MILLET": { allergyRisk: "Low", chokingRisk: "Low", serve6to8: "<h4 class='font-semibold'>6-8 Months:</h4><p>Serve cooked millet as a thick porridge on a pre-loaded spoon. You can also let it cool and form it into soft, graspable strips.</p>", serve9to12: "<h4 class='font-semibold mt-4'>9-12 Months:</h4><p>Continue serving as a porridge or in soft strips. You can also use millet flour for baking.</p>" },
    "OATMEAL": { allergyRisk: "Low (Oats are not a top 9 allergen, but check for cross-contamination if Celiac disease is a concern)", chokingRisk: "Low", serve6to8: "<h4 class='font-semibold'>6-8 Months:</h4><p>Make oatmeal thick so it's not runny. Offer it on a pre-loaded spoon (like a Go-O utensil) that you hand to your baby. You can also let them scoop it with their hands. Mix in allergens like thinned peanut butter or yogurt.</p>", serve9to12: "<h4 class='font-semibold mt-4'>9-12 Months:</h4><p>Continue serving as above. You can also bake oatmeal into 'oatmeal fingers' or muffins for an easy-to-hold, portable option.</p>" },
    "BUCKWHEAT": { allergyRisk: "Low (though allergy is possible)", chokingRisk: "Low", serve6to8: "<h4 class='font-semibold'>6-8 Months:</h4><p>Serve cooked buckwheat groats as a thick porridge. Buckwheat flour can be used to make baby pancakes (soba noodles are also made from buckwheat, but watch sodium).</p>", serve9to12: "<h4 class='font-semibold mt-4'>9-12 Months:</h4><p>Continue serving as a porridge or in pancakes. Cooked groats can be served for pincer practice.</p>" },
    "WAFFLES": { allergyRisk: "High (often contain Wheat, Egg, Dairy)", chokingRisk: "Low", serve6to8: "<h4 class='font-semibold'>6-8 Months:</h4><p>Serve homemade or low-sodium, low-sugar store-bought waffles. Cut into long, 1-inch wide strips. Toast lightly to make them easier to grip but not hard or crunchy.</p>", serve9to12: "<h4 class='font-semibold mt-4'>9-12 Months:</h4><p>Continue serving in strips or cut into small, bite-sized pieces.</p>" },
    "HEALTHY MUFFINS": { allergyRisk: "High (often contain Wheat, Egg, Dairy, Nuts)", chokingRisk: "Low (if moist)", serve6to8: "<h4 class='font-semibold'>6-8 Months:</h4><p>Bake homemade muffins with no sugar or salt, using fruit for sweetness. Ensure they are moist, not dry and crumbly. Serve a whole mini-muffin or a large piece of a regular muffin.</p>", serve9to12: "<h4 class='font-semibold mt-4'>9-12 Months:</h4><p>Continue serving large pieces, or break into smaller, soft crumbles for pincer grasp practice.</p>" },
    "PASTA": { allergyRisk: "High (Wheat, often Egg)", chokingRisk: "Low", serve6to8: "<h4 class='font-semibold'>6-8 Months:</h4><p>Cook pasta until very soft. Serve large, easy-to-grip shapes like rotini, penne, or rigatoni. You can toss it with a thin, low-sodium sauce.</p>", serve9to12: "<h4 class='font-semibold mt-4'>9-12 Months:</h4><p>Continue serving large shapes. As pincer grasp develops, you can offer smaller, soft-cooked pasta like orzo or ditalini.</p>" },
    "COUSCOUS": { allergyRisk: "High (Wheat)", chokingRisk: "Low", serve6to8: "<h4 class='font-semibold'>6-8 Months:</h4><p>Serve plain, cooked couscous on a tray for baby to rake up with their hands. You can also mix it with yogurt or a purée to help it clump together.</p>", serve9to12: "<h4 class='font-semibold mt-4'>9-12 Months:</h4><p>Continue to serve as is, encouraging pincer grasp development.</p>" },
    "POLENTA": { allergyRisk: "Low", chokingRisk: "Low", serve6to8: "<h4 class='font-semibold'>6-8 Months:</h4><p>Serve creamy polenta on a pre-loaded spoon. Or, let it cool and solidify, then cut it into long, thick strips for baby to hold.</p>", serve9to12: "<h4 class='font-semibold mt-4'>9-12 Months:</h4><p>Continue serving as a creamy porridge or in solid strips. You can also cut the solid polenta into small, bite-sized cubes.</p>" },
    "CORNMEAL": { allergyRisk: "Low", chokingRisk: "Low", serve6to8: "<h4 class='font-semibold'>6-8 Months:</h4><p>Serve as a thick porridge (like polenta or grits) on a pre-loaded spoon. Cornmeal can also be used to make baby-friendly cornbread, served in strips.</p>", serve9to12: "<h4 class='font-semibold mt-4'>9-12 Months:</h4><p>Continue serving as a porridge or in cornbread strips/cubes.</p>" },
    "BREAD": { allergyRisk: "High (Wheat)", chokingRisk: "Low (when toasted)", serve6to8: "<h4 class='font-semibold'>6-8 Months:</h4><p>Serve a large strip of lightly toasted bread. The toast makes it less gummy and less of a choking risk. Avoid very soft, fresh bread. You can top with a very thin layer of mashed avocado or thinned peanut butter.</p>", serve9to12: "<h4 class='font-semibold mt-4'>9-12 Months:</h4><p>Continue serving toasted strips, or cut into small, bite-sized pieces of toast for pincer practice.</p>" },
    "GNOCCHI": { allergyRisk: "High (often contains Wheat, Egg, Dairy)", chokingRisk: "Medium", serve6to8: "<h4 class='font-semibold'>6-8 Months:</h4><p>Cook gnocchi until very soft. The shape can be a risk, so it's best to smash it slightly with a fork before serving.</p>", serve9to12: "<h4 class='font-semibold mt-4'>9-12 Months:</h4><p>Continue to smash gnocchi. As baby gets more proficient at chewing, you can cut them in half lengthwise.</p>" },
    "TORTILLA": { allergyRisk: "Medium (can be Wheat or Corn)", chokingRisk: "Low", serve6to8: "<h4 class='font-semibold'>6-8 Months:</h4><p>Serve a soft corn or whole wheat tortilla cut into long, wide strips. You can warm it slightly to make it more pliable. Great for making a simple quesadilla (with melted mozzarella) and cutting into strips.</p>", serve9to12: "<h4 class='font-semibold mt-4'>9-12 Months:</h4><p>Continue serving in strips or cut into small, bite-sized triangles.</p>" },
    "FARRO": { allergyRisk: "High (Wheat)", chokingRisk: "Low", serve6to8: "<h4 class='font-semibold'>6-8 Months:</h4><p>Cook farro until very soft and serve mixed into other foods like yogurt or a mash to make it easier for baby to eat.</p>", serve9to12: "<h4 class='font-semibold mt-4'>9-12 Months:</h4><p>Serve soft-cooked farro on a tray for baby to practice picking up with their fingers.</p>" },
    "BARLEY": { allergyRisk: "Low (contains gluten, but not a top 9 allergen)", chokingRisk: "Low", serve6to8: "<h4 class='font-semibold'>6-8 Months:</h4><p>Cook barley until very soft and serve as a thick porridge or mixed into other foods.</p>", serve9to12: "<h4 class='font-semibold mt-4'>9-12 Months:</h4><p>Serve soft-cooked barley as is for pincer grasp practice.</p>" },
    "BULGUR": { allergyRisk: "High (Wheat)", chokingRisk: "Low", serve6to8: "<h4 class='font-semibold'>6-8 Months:</h4><p>Cook fine bulgur until soft and serve on its own for baby to rake up, or mix with yogurt to help it clump.</p>", serve9to12: "<h4 class='font-semibold mt-4'>9-12 Months:</h4><p>Continue serving as is to encourage pincer grasp development.</p>" },
    "BROWN RICE": { allergyRisk: "Low", chokingRisk: "Low", serve6to8: "<h4 class='font-semibold'>6-8 Months:</h4><p>Cook brown rice until very soft. You can mash it slightly and offer on a pre-loaded spoon, or press it into clumps for baby to pick up.</p>", serve9to12: "<h4 class='font-semibold mt-4'>9-12 Months:</h4><p>Serve soft-cooked rice on a tray for baby to practice their pincer grasp on.</p>" },
    "QUINOA": { allergyRisk: "Low", chokingRisk: "Low", serve6to8: "<h4 class='font-semibold'>6-8 Months:</h4><p>Cook quinoa until soft and serve as a thick porridge, or mix with other foods to help it bind together.</p>", serve9to12: "<h4 class='font-semibold mt-4'>9-12 Months:</h4><p>Serve cooked quinoa on its own for pincer grasp practice.</p>" },
    "FREEKEH": { allergyRisk: "High (Wheat)", chokingRisk: "Low", serve6to8: "<h4 class='font-semibold'>6-8 Months:</h4><p>Cook freekeh until very soft and serve mixed with other foods like mashed sweet potato or yogurt.</p>", serve9to12: "<h4 class='font-semibold mt-4'>9-12 Months:</h4><p>Serve soft-cooked freekeh on its own for baby to practice picking up.</p>" },

    // Fruits
    "AVOCADO": { allergyRisk: "Low", chokingRisk: "Low", serve6to8: "<h4 class='font-semibold'>6-8 Months:</h4><p>Serve ripe avocado in long, thick spears (about the width of two adult fingers). You can roll the spears in a 'duster' like crushed cereal, hemp seeds, or nutritional yeast to make it less slippery and easier to grip.</p>", serve9to12: "<h4 class='font-semibold mt-4'>9-12 Months:</h4><p>As baby develops a pincer grasp, you can offer ripe avocado in small, pincer-sized cubes. You can also continue to serve spears or mashed on a pre-loaded spoon.</p>" },
    "TOMATOES": { allergyRisk: "Low (though acidic)", chokingRisk: "Medium (cherry/grape tomatoes)", serve6to8: "<h4 class='font-semibold'>6-8 Months:</h4><p>Offer a large, ripe tomato wedge (from a beefsteak or heirloom tomato) for baby to suck on. Cherry or grape tomatoes are a choking hazard and should be avoided at this age unless quartered and cooked down into a sauce.</p>", serve9to12: "<h4 class='font-semibold mt-4'>9-12 Months:</h4><p>You can now offer small cherry or grape tomatoes, but they <strong>must be quartered lengthwise</strong> to reduce the choking risk.</p>" },
    "ORANGE": { allergyRisk: "Low (though acidic)", chokingRisk: "Medium (membrane and seeds)", serve6to8: "<h4 class='font-semibold'>6-8 Months:</h4><p>Serve a large, supreme-d segment of a large orange (like a navel orange) with all membrane and seeds removed. Baby will mostly suck the juice out of it.</p>", serve9to12: "<h4 class='font-semibold mt-4'>9-12 Months:</h4><p>Continue serving supreme-d segments, or cut them into small, bite-sized pieces with membrane removed.</p>" },
    "LEMON & LIME": { allergyRisk: "Low (though acidic)", chokingRisk: "Low", serve6to8: "<h4 class='font-semibold'>6-8 Months:</h4><p>These are too sour to serve on their own. Squeeze a small amount onto other foods like fish, chicken, or avocado to introduce the flavor. You can also offer a large wedge for a supervised taste - get your camera ready for the reaction!</p>", serve9to12: "<h4 class='font-semibold mt-4'>9-12 Months:</h4><p>Continue using as a flavor enhancer in cooking.</p>" },
    "PAPAYA": { allergyRisk: "Low", chokingRisk: "Low", serve6to8: "<h4 class='font-semibold'>6-8 Months:</h4><p>Ensure the papaya is ripe and soft. Remove all seeds and skin. Serve in long, thick spears.</p>", serve9to12: "<h4 class='font-semibold mt-4'>9-12 Months:</h4><p>Continue serving in spears or offer small, bite-sized cubes of ripe papaya.</p>" },
    "PINEAPPLE": { allergyRisk: "Low (though acidic)", chokingRisk: "Medium (fibrous)", serve6to8: "<h4 class='font-semibold'>6-8 Months:</h4><p>Use very ripe pineapple. Serve a large, long spear (without the hard core) for baby to gnaw on. Supervise closely.</p>", serve9to12: "<h4 class='font-semibold mt-4'>9-12 Months:</h4><p>Continue with ripe spears or offer small, bite-sized chunks of very ripe pineapple.</p>" },
    "KIWIFRUIT": { allergyRisk: "Low (though acidic)", chokingRisk: "Low", serve6to8: "<h4 class='font-semibold'>6-8 Months:</h4><p>Peel the kiwi and serve in large spears or halves. The skin can be left on a portion as a handle.</p>", serve9to12: "<h4 class='font-semibold mt-4'>9-12 Months:</h4><p>Serve in spears or cut into small, bite-sized pieces.</p>" },
    "MANGO": { allergyRisk: "Low", chokingRisk: "Low (can be slippery)", serve6to8: "<h4 class='font-semibold'>6-8 Months:</h4><p>Use very ripe mango. Serve in long, thick spears. You can leave some skin on as a handle, or roll it in a 'duster' (crushed cereal) to make it less slippery.</p>", serve9to12: "<h4 class='font-semibold mt-4'>9-12 Months:</h4><p>Continue with spears or offer small, bite-sized cubes of ripe mango.</p>" },
    "STARFRUIT": { allergyRisk: "Low", chokingRisk: "Medium", serve6to8: "<h4 class='font-semibold'>6-8 Months:</h4><p>Use very ripe starfruit. The star shape is a hazard. It is best to cut off the pointy star edges and serve the inner flesh in a long strip.</p>", serve9to12: "<h4 class='font-semibold mt-4'>9-12 Months:</h4><p>Continue serving in safe strips, or finely dice the ripe fruit.</p>" },
    "FIGS": { allergyRisk: "Low", chokingRisk: "Low", serve6to8: "<h4 class='font-semibold'>6-8 Months:</h4><p>Serve fresh, ripe figs. Cut them in half or quarters lengthwise.</p>", serve9to12: "<h4 class='font-semibold mt-4'>9-12 Months:</h4><p>Continue serving in quarters, or cut into smaller, bite-sized pieces.</p>" },
    "BANANA": { allergyRisk: "Low", chokingRisk: "Low (when ripe)", serve6to8: "<h4 class='font-semibold'>6-8 Months:</h4><p>Serve a whole, ripe banana, but leave the bottom third of the peel on as a 'handle' for baby to grip. You can also serve it in long spears, rolled in a 'duster' (like crushed cereal or hemp seeds) to make it less slippery.</p>", serve9to12: "<h4 class='font-semibold mt-4'>9-12 Months:</h4><p>As baby develops a pincer grasp, you can offer small, bite-sized pieces of ripe banana. You can also continue to serve it in spears or mashed.</p>" },
    "COCONUT": { allergyRisk: "Medium (classified as a tree nut by FDA)", chokingRisk: "High (shredded/dried)", serve6to8: "<h4 class='font-semibold'>6-8 Months:</h4><p>Do not serve dried or shredded coconut. You can offer a large, long piece of fresh coconut flesh to gnaw on (supervise closely). Unsweetened coconut milk can be used in cooking, and unsweetened coconut cream can be mixed with fruit.</p>", serve9to12: "<h4 class='font-semibold mt-4'>9-12 Months:</h4><p>Continue as above. Avoid dried/shredded coconut until much older.</p>" },
    "WATERMELON": { allergyRisk: "Low", chokingRisk: "Low (can be watery)", serve6to8: "<h4 class='font-semibold'>6-8 Months:</h4><p>Ensure it's seedless. Serve a large, long spear with the rind on as a handle. Supervise closely as large watery bites can cause gagging.</p>", serve9to12: "<h4 class='font-semibold mt-4'>9-12 Months:</h4><p>Continue with spears or offer small, bite-sized chunks of seedless watermelon.</p>" },
    "HONEYDEW": { allergyRisk: "Low", chokingRisk: "Low", serve6to8: "<h4 class='font-semibold'>6-8 Months:</h4><p>Use ripe, soft honeydew. Serve in long, thick spears with the rind removed.</p>", serve9to12: "<h4 class='font-semibold mt-4'>9-12 Months:</h4><p>Continue with spears or offer small, bite-sized cubes of ripe melon.</p>" },
    "CANTALOUPE": { allergyRisk: "Low", chokingRisk: "Low", serve6to8: "<h4 class='font-semibold'>6-8 Months:</h4><p>Use ripe, soft cantaloupe. Serve in long, thick spears with the rind removed.</p>", serve9to12: "<h4 class='font-semibold mt-4'>9-12 Months:</h4><p>Continue with spears or offer small, bite-sized cubes of ripe melon.</p>" },
    "APPLESAUCE": { allergyRisk: "Low", chokingRisk: "Low", serve6to8: "<h4 class='font-semibold'>6-8 Months:</h4><p>Choose unsweetened applesauce. Offer on a pre-loaded spoon for baby to bring to their own mouth.</p>", serve9to12: "<h4 class='font-semibold mt-4'>9-12 Months:</h4><p>Continue serving on a pre-loaded spoon.</p>" },
    "RASPBERRIES": { allergyRisk: "Low", chokingRisk: "Low", serve6to8: "<h4 class='font-semibold'>6-8 Months:</h4><p>Serve a whole, large, ripe raspberry for baby to palm and mash in their mouth. You can also lightly flatten it with a fork first.</p>", serve9to12: "<h4 class='font-semibold mt-4'>9-12 Months:</h4><p>Continue serving whole or cut in half.</p>" },
    "BLUEBERRIES": { allergyRisk: "Low", chokingRisk: "High (when whole)", serve6to8: "<h4 class='font-semibold'>6-8 Months:</h4><p>Blueberries are a choking hazard. Serve them smashed or flattened. You can cook them down into a compote to mix with yogurt or oatmeal.</p>", serve9to12: "<h4 class='font-semibold mt-4'>9-12 Months:</h4><p>Continue to smash or flatten blueberries. As baby's pincer grasp and chewing skills improve, you can begin to offer them cut in half, and eventually whole, with close supervision.</p>" },
    "STRAWBERRIES": { allergyRisk: "Low", chokingRisk: "Low", serve6to8: "<h4 class='font-semibold'>6-8 Months:</h4><p>Serve a whole, large strawberry (with stem/leaves removed) for baby to gnaw on. You can also serve it cut in half or quarters lengthwise.</p>", serve9to12: "<h4 class='font-semibold mt-4'>9-12 Months:</h4><p>Continue serving as above, or thinly slice for pincer grasp practice.</p>" },
    "GRAPES": { allergyRisk: "Low", chokingRisk: "Very High", serve6to8: "<h4 class='font-semibold'>6-8 Months:</h4><p><strong>NEVER</strong> serve whole or halved grapes. They are a severe choking hazard. At this age, it's safest to avoid them or cook them down into a sauce.</p>", serve9to12: "<h4 class='font-semibold mt-4'>9-12 Months:</h4><p>Grapes MUST be <strong>quartered lengthwise</strong> to be served safely. The round shape is the hazard, so cutting them into long, thin pieces is essential. Supervise closely.</p>" },
    "PEACHES": { allergyRisk: "Low", chokingRisk: "Low", serve6to8: "<h4 class='font-semibold'>6-8 Months:</h4><p>Use very ripe, soft peaches. Serve in large spears or halves with the pit removed. You can leave the skin on for better grip.</p>", serve9to12: "<h4 class='font-semibold mt-4'>9-12 Months:</h4><p>Continue serving in spears or offer small, bite-sized pieces of ripe peach.</p>" },
    "PEARS": { allergyRisk: "Low", chokingRisk: "Low", serve6to8: "<h4 class='font-semibold'>6-8 Months:</h4><p>Use very ripe, soft pears. Serve in large spears or halves. You can leave the skin on for better grip.</p>", serve9to12: "<h4 class='font-semibold mt-4'>9-12 Months:</h4><p>Continue serving in spears or offer small, bite-sized pieces of ripe pear.</p>" },
    "APPLES": { allergyRisk: "Low", chokingRisk: "High (when raw)", serve6to8: "<h4 class='font-semibold'>6-8 Months:</h4><p><strong>NEVER</strong> serve raw, hard apple pieces or whole apples. They are a major choking hazard.</p><p class='mt-2'>Serve in one of two ways:<br>1. Offer unsweetened applesauce on a pre-loaded spoon.<br>2. Cook apple spears (with skin removed) by steaming or roasting them until they are very soft all the way through. They should be easily smushed between your fingers.</p>", serve9to12: "<h4 class='font-semibold mt-4'>9-12 Months:</h4><p>Continue serving soft-cooked apples or applesauce. As baby develops, you can offer shredded raw apple, which is safer than chunks. Do not serve hard, raw apple chunks.</p>" },

    // Plant Protein
    "TOFU": { allergyRisk: "High (Top 9 Allergen - Soy)", chokingRisk: "Low", serve6to8: "<h4 class='font-semibold'>6-8 Months:</h4><p>Use firm or extra-firm tofu. Cut into long, thick spears. You can pan-fry it lightly to give it a better 'skin' for gripping. Introduce soy on its own and watch for reaction.</p>", serve9to12: "<h4 class='font-semibold mt-4'>9-12 Months:</h4><p>Continue serving in spears or cut into small, bite-sized cubes for pincer grasp practice.</p>" },
    "EDAMAME": { allergyRisk: "High (Top 9 Allergen - Soy)", chokingRisk: "High (when whole)", serve6to8: "<h4 class='font-semibold'>6-8 Months:</h4><p>Serve shelled, cooked edamame. You must smash or flatten the beans to reduce the choking risk. You can also blend it into a dip.</p>", serve9to12: "<h4 class='font-semibold mt-4'>9-12 Months:</h4><p>Continue to serve smashed. As chewing skills improve, you can serve them whole with close supervision.</p>" },
    "PEANUTS": { allergyRisk: "High (Top 9 Allergen)", chokingRisk: "High (when whole or in gobs)", serve6to8: "<h4 class='font-semibold'>6-8 Months:</h4><p><strong>NEVER</strong> serve whole peanuts, peanut pieces, or thick, sticky gobs of peanut butter, as these are severe choking hazards.</p><p class='mt-2'><strong>To serve safely:</strong><br>1. Thin a small amount (1-2 teaspoons) of smooth peanut butter with water, breastmilk, or formula to a thin, 'sauce-like' consistency and offer on a spoon.<br>2. Or, stir a small amount of smooth peanut butter into yogurt or oatmeal.<br>3. Or, spread a *very* thin layer (almost see-through) on a piece of toast, cut into strips.</p><p class='mt-2'><strong>Allergy Info:</strong> Peanuts are a top allergen. Introduce it early and often (after 6 months) to help prevent allergy. Start with a tiny amount.</p>", serve9to12: "<h4 class='font-semibold mt-4'>9-12 Months:</h4><p>Continue serving as above. You can still spread a thin layer on toast or mix into other foods. Avoid whole peanuts until at least age 4-5.</p>" },
    "ALMONDS": { allergyRisk: "High (Top 9 Allergen - Tree Nuts)", chokingRisk: "High (when whole)", serve6to8: "<h4 class='font-semibold'>6-8 Months:</h4><p><strong>NEVER</strong> serve whole almonds. Serve smooth almond butter, prepared the same way as peanut butter (thinned with water/milk or stirred into foods). You can also use almond flour in baking.</p>", serve9to12: "<h4 class='font-semibold mt-4'>9-12 Months:</h4><p>Continue serving thinned almond butter or using almond flour. Avoid whole nuts.</p>" },
    "WHITE BEANS": { allergyRisk: "Low", chokingRisk: "Medium", serve6to8: "<h4 class='font-semibold'>6-8 Months:</h4><p>Serve cooked, no-salt-added white beans. Smash them with a fork or the back of a spoon to alter their round shape.</p>", serve9to12: "<h4 class='font-semibold mt-4'>9-12 Months:</h4><p>Continue serving smashed. As baby's chewing improves, you can offer them whole with supervision.</p>" },
    "CHICKPEAS": { allergyRisk: "Low", chokingRisk: "Medium", serve6to8: "<h4 class='font-semibold'>6-8 Months:</h4><p>Serve cooked, no-salt-added chickpeas. Smash them to reduce the choking risk. Hummus (low-sodium) is another great way to serve them.</p>", serve9to12: "<h4 class='font-semibold mt-4'>9-12 Months:</h4><p>Continue serving smashed or as hummus. Well-cooked chickpeas can be served whole once chewing is proficient.</p>" },
    "BLACK BEANS": { allergyRisk: "Low", chokingRisk: "Medium", serve6to8: "<h4 class='font-semibold'>6-8 Months:</h4><p>Serve cooked, no-salt-added black beans. Smash them with a fork before serving.</p>", serve9to12: "<h4 class='font-semibold mt-4'>9-12 Months:</h4><p>Continue serving smashed. As chewing improves, you can serve them whole.</p>" },
    "KIDNEY BEANS": { allergyRisk: "Low", chokingRisk: "Medium", serve6to8: "<h4 class='font-semibold'>6-8 Months:</h4><p>Serve cooked, no-salt-added kidney beans. Smash them well before serving.</p>", serve9to12: "<h4 class='font-semibold mt-4'>9-12 Months:</h4><p>Continue serving smashed. Can be offered whole once chewing is well-established.</p>" },
    "LENTILS": { allergyRisk: "Low", chokingRisk: "Low", serve6to8: "<h4 class='font-semibold'>6-8 Months:</h4><p>Cook lentils until very soft. They are small and low-risk. Serve on a tray for baby to rake up, or mixed into other foods.</p>", serve9to12: "<h4 class='font-semibold mt-4'>9-12 Months:</h4><p>Continue to serve as is, encouraging pincer grasp development.</p>" },
    "ALMOND BUTTER": { allergyRisk: "High (Top 9 Allergen - Tree Nuts)", chokingRisk: "High (in gobs)", serve6to8: "<h4 class='font-semibold'>6-8 Months:</h4><p>Serve exactly like peanut butter: thinned with water/milk to a sauce-like consistency, or stirred into oatmeal/yogurt, or spread *very* thinly on a toast strip.</p>", serve9to12: "<h4 class='font-semibold mt-4'>9-12 Months:</h4><p>Continue serving safely as above. Avoid large gobs.</p>" },
    "PEANUT BUTTER": { allergyRisk: "High (Top 9 Allergen)", chokingRisk: "High (in gobs)", serve6to8: "<h4 class='font-semibold'>6-8 Months:</h4><p>See PEANUTS. Always serve thinned out or a very thin layer on toast.</p>", serve9to12: "<h4 class='font-semibold mt-4'>9-12 Months:</h4><p>See PEANUTS. Continue with safe serving methods.</p>" },
    "SEEDS": { allergyRisk: "Medium (Sesame is a Top 9 Allergen)", chokingRisk: "Low", serve6to8: "<h4 class='font-semibold'>6-8 Months:</h4><p>Serve ground seeds (chia, flax, hemp) mixed into other foods like oatmeal or yogurt. Tahini (sesame paste) can be introduced by stirring a small amount into yogurt.</p>", serve9to12: "<h4 class='font-semibold mt-4'>9-12 Months:</h4><p>Continue serving ground seeds or tahini. Small whole seeds like hemp or chia are generally safe at this age.</p>" },

    // Meat
    "FISH": { allergyRisk: "High (Top 9 Allergen)", chokingRisk: "Low (if deboned)", serve6to8: "<h4 class='font-semibold'>6-8 Months:</h4><p>Serve a large, soft, flaky piece of low-mercury fish like salmon, cod, or tilapia. Meticulously check for and remove all bones.</p>", serve9to12: "<h4 class='font-semibold mt-4'>9-12 Months:</h4><p>Continue serving large pieces or break into smaller flakes for pincer grasp practice.</p>" },
    "TUNA": { allergyRisk: "High (Top 9 Allergen - Fish)", chokingRisk: "Low", serve6to8: "<h4 class='font-semibold'>6-8 Months:</h4><p>Choose 'light' or 'skipjack' tuna packed in water (lower in mercury). Serve plain, mashed with a little yogurt or avocado. Ensure it's not too dry.</p>", serve9to12: "<h4 class='font-semibold mt-4'>9-12 Months:</h4><p>Continue serving as a mash or salad. Limit tuna intake due to mercury content.</p>" },
    "SARDINES": { allergyRisk: "High (Top 9 Allergen - Fish)", chokingRisk: "Low", serve6to8: "<h4 class='font-semibold'>6-8 Months:</h4><p>Choose sardines packed in water with no salt added. The bones are very soft and edible. You can serve a whole sardine or mash it onto a toast strip.</p>", serve9to12: "<h4 class='font-semibold mt-4'>9-12 Months:</h4><p>Continue serving whole or mashed.</p>" },
    "SALMON": { allergyRisk: "High (Top 9 Allergen - Fish)", chokingRisk: "Low (if deboned)", serve6to8: "<h4 class='font-semibold'>6-8 Months:</h4><p>Cook salmon until soft and flaky. Offer a large piece (size of two adult fingers) and make sure all bones are removed.</p>", serve9to12: "<h4 class='font-semibold mt-4'>9-12 Months:</h4><p>Continue offering a large piece or flake it into smaller pieces for pincer practice.</p>" },
    "SHRIMP": { allergyRisk: "High (Top 9 Allergen - Shellfish)", chokingRisk: "Medium", serve6to8: "<h4 class='font-semibold'>6-8 Months:</h4><p>Cook shrimp thoroughly. You can offer a whole, large butterflied shrimp for baby to gnaw on, or finely mince it and add to other foods.</p>", serve9to12: "<h4 class='font-semibold mt-4'>9-12 Months:</h4><p>Finely chop cooked shrimp for pincer grasp practice.</p>" },
    "BEEF, SLICED": { allergyRisk: "Low", chokingRisk: "High (if tough)", serve6to8: "<h4 class='font-semibold'>6-8 Months:</h4><p>Use a slow cooker or pressure cooker to make beef very tender. Offer a large, long strip (about the size of two adult fingers) that is shreddable. Baby will mostly suck the juices.</p>", serve9to12: "<h4 class='font-semibold mt-4'>9-12 Months:</h4><p>Continue serving very tender strips, or offer shredded beef.</p>" },
    "BEEF, GROUND": { allergyRisk: "Low", chokingRisk: "Low", serve6to8: "<h4 class='font-semibold'>6-8 Months:</h4><p>Cook ground beef and serve as a large, soft meatball or a patty cut into strips. Ensure it's moist, not dry and crumbly.</p>", serve9to12: "<h4 class='font-semibold mt-4'>9-12 Months:</h4><p>Serve in soft patties/meatballs, or break into small crumbles for pincer practice.</p>" },
    "CHICKEN": { allergyRisk: "Low", chokingRisk: "Medium (When dry, tough, or in cubes)", serve6to8: "<h4 class='font-semibold'>6-8 Months:</h4><p><strong>NEVER</strong> serve in cubes or chunks. Chicken must be very soft and moist. The safest way is to offer a large, long strip (about the size of two adult fingers) of *dark meat* (like thigh or drumstick), which is more tender and iron-rich. Ensure it's cooked through and any gristle/bone is removed. You can also serve ground chicken in a soft-cooked meatball or patty.</p>", serve9to12: "<h4 class='font-semibold mt-4'>9-12 Months:</h4><p>As baby's grasp improves, you can offer smaller, shredded pieces of moist chicken. Continue to avoid hard, dry cubes. Ground chicken patties or meatballs are still an excellent choice.</p>" },
    "LAMB": { allergyRisk: "Low", chokingRisk: "High (if tough)", serve6to8: "<h4 class='font-semibold'>6-8 Months:</h4><p>Serve very tender, slow-cooked lamb. Offer a large strip of meat for baby to gnaw on. A lamb chop bone (with small bits of meat removed) can also be a good teether, with supervision.</p>", serve9to12: "<h4 class='font-semibold mt-4'>9-12 Months:</h4><p>Continue with very tender strips or offer shredded lamb.</p>" },
    "TURKEY": { allergyRisk: "Low", chokingRisk: "Medium (can be dry)", serve6to8: "<h4 class='font-semibold'>6-8 Months:</h4><p>Serve moist, dark meat turkey in a long, thick strip. Ground turkey made into a soft patty or meatball is also excellent.</p>", serve9to12: "<h4 class='font-semibold mt-4'>9-12 Months:</h4><p>Continue with moist strips of dark meat, or offer shredded turkey. Ground turkey crumbles are also good for pincer practice.</p>" },
    "PORK": { allergyRisk: "Low", chokingRisk: "High (if tough)", serve6to8: "<h4 class='font-semibold'>6-8 Months:</h4><p>Serve very tender, slow-cooked pork (like pulled pork, no sauce). Offer a large strip of the tender meat.</p>", serve9to12: "<h4 class='font-semibold mt-4'>9-12 Months:</h4><p>Continue with very tender strips or offer shredded pork.</p>" },

    // Dairy & Eggs
    "YOGURT": { allergyRisk: "High (Top 9 Allergen - Cow's Milk)", chokingRisk: "Low", serve6to8: "<h4 class='font-semibold'>6-8 Months:</h4><p>Serve plain, whole-milk (full-fat) yogurt with no added sugars. Offer it on a pre-loaded spoon for baby to grab. You can also mix in thinned peanut butter or fruit purées (once those are introduced).</p><p class='mt-2'><strong>Allergy Info:</strong> This is a top allergen. Introduce it on its own and wait 3-5 days before other new allergens. Start with a small amount.</p>", serve9to12: "<h4 class='font-semibold mt-4'>9-12 Months:</h4><p>Continue serving plain, whole-milk yogurt. You can start to mix in soft fruits or berries (smashed or quartered).</p>" },
    "EGGS": { allergyRisk: "High (Top 9 Allergen)", chokingRisk: "Low", serve6to8: "<h4 class='font-semibold'>6-8 Months:</h4><p>Offer fully-cooked egg only. A great way is to make a simple 'omelet strip' by whisking one egg and cooking it flat in a pan. Cut it into long, 1-inch wide strips for baby to hold.</p><p class='mt-2'><strong>Allergy Info:</strong> Egg is a top allergen. Introduce it on its own and wait 3-5 days before introducing other new allergens. Start with a small amount.</p>", serve9to12: "<h4 class='font-semibold mt-4'>9-12 Months:</h4><p>You can serve scrambled eggs (cooked through) or chopped hard-boiled eggs for pincer grasp practice. Continue offering omelet strips as well.</p>" },
    "MOZZARELLA": { allergyRisk: "High (Top 9 Allergen - Cow's Milk)", chokingRisk: "Medium (melted strings)", serve6to8: "<h4 class='font-semibold'>6-8 Months:</h4><p>Serve fresh, full-fat mozzarella. Offer a large piece for baby to gnaw on, or serve shredded mozzarella. Melted mozzarella can be stringy and difficult, but is fine in a thin layer on a quesadilla strip.</p>", serve9to12: "<h4 class='font-semibold mt-4'>9-12 Months:</h4><p>Continue serving shredded or in small, bite-sized cubes of fresh mozzarella.</p>" },
    "RICOTTA CHEESE": { allergyRisk: "High (Top 9 Allergen - Cow's Milk)", chokingRisk: "Low", serve6to8: "<h4 class='font-semibold'>6-8 Months:</h4><p>Serve whole milk ricotta on a pre-loaded spoon, or spread thinly on a toast strip.</p>", serve9to12: "<h4 class='font-semibold mt-4'>9-12 Months:</h4><p>Continue serving as above.</p>" },
    "COTTAGE CHEESE": { allergyRisk: "High (Top 9 Allergen - Cow's Milk)", chokingRisk: "Low", serve6to8: "<h4 class='font-semibold'>6-8 Months:</h4><p>Choose plain, whole milk cottage cheese. The curds are a great texture. Serve on a pre-loaded spoon or on a tray for baby to rake up.</p>", serve9to12: "<h4 class='font-semibold mt-4'>9-12 Months:</h4><p>Continue serving as is, encouraging self-feeding.</p>" },

    // Other
    "WATER": { allergyRisk: "Low", chokingRisk: "Low", serve6to8: "<h4 class='font-semibold'>6-8 Months:</h4><p>Offer a small amount (1-2 oz) of water in an open cup or a straw cup with meals. This is primarily for learning to drink, not for hydration (which still comes from breastmilk/formula).</p>", serve9to12: "<h4 class='font-semibold mt-4'>9-12 Months:</h4><p>Continue offering water with all meals in an open cup or straw cup. Baby will gradually get better at sipping and drinking.</p>" },
    "SPICES & HERBS": { allergyRisk: "Low", chokingRisk: "Low", serve6to8: "<h4 class='font-semibold'>6-8 Months:</h4><p>Introduce flavors early! Add small amounts of spices like cinnamon, cumin, garlic powder, or paprika to baby's food. Finely chop fresh herbs like parsley or cilantro and mix them in.</p>", serve9to12: "<h4 class='font-semibold mt-4'>9-12 Months:</h4><p>Continue to explore a variety of spices and herbs to expand baby's palate. Avoid very spicy seasonings like cayenne initially.</p>" }
};

export const recommendationData: { [key: string]: { title: string; foods: string[]; message: string; } } = {
    'too_young': { title: "Not Quite 6 Months", foods: [], message: "Most pediatricians recommend starting solids around 6 months, when baby shows all signs of readiness. See the 'Learn' tab for more info!" },
    '6_months': { title: "6 Months: First Tastes", foods: ["AVOCADO", "SWEET POTATO", "BANANA", "OATMEAL", "EGGPLANT", "ZUCCHINI", "BROCCOLI", "CARROTS", "EGGS", "YOGURT", "WATER"], message: "Focus on soft, single-ingredient foods. Offer soft-cooked spears or large pieces. This is a great time to safely introduce top allergens like egg and yogurt (see Learn tab!). Offer sips of water with meals." },
    '7_8_months': { title: "7-8 Months: Exploring Textures", foods: ["CHICKEN", "SALMON", "TOFU", "LENTILS", "BREAD", "PEANUT BUTTER", "ALMOND BUTTER", "APPLES", "PEARS", "PASTA", "SPICES & HERBS"], message: "Baby is likely getting better at mashing and moving food. You can offer softer proteins and continue introducing allergens. Now is a great time to add spices (like cinnamon or garlic powder) to foods!" },
    '9_11_months': { title: "9-11 Months: Pincer Grasp Practice", foods: ["PEAS", "BLUEBERRIES", "RASPBERRIES", "CUCUMBER", "COTTAGE CHEESE", "BEEF, GROUND", "BLACK BEANS", "CORN", "GRAPES", "TOMATOES"], message: "Baby may be starting to use their pincer grasp. Offer smaller, soft-cooked foods (e.g., cut grapes in quarters, smash blueberries/peas) to help them practice." },
    '12_plus': { title: "12+ Months: Try Everything!", foods: flatFoodList, message: "By 12 months, your baby can eat most of what you eat (with appropriate modifications for salt, spice, and choking hazards). Work your way through the rest of the 100 foods list!" }
};

export const guidesData = [
    { 
        title: "How Many Meals a Day?", 
        icon: "utensils-crossed",
        content: `<p>Follow your baby's lead! This is a general guide, but every baby is different. Focus on exploration, not volume.</p><ul class="list-disc list-outside space-y-2 pl-5"><li><strong>~6 Months:</strong> Start with <strong>1 meal</strong> a day. This is just for practice. Timing doesn't matter, just pick a time when baby is happy, rested, and not starving.</li><li><strong>~7-8 Months:</strong> When baby seems to be getting the hang of it, you can move to <strong>2 meals</strong> a day.</li><li><strong>~9-11 Months:</strong> Baby is likely a pro by now and can handle <strong>3 meals</strong> a day, often at the same time as the family (breakfast, lunch, dinner).</li></ul><p class="mt-2"><strong>Remember:</strong> Breastmilk or formula is still their primary source of nutrition until age 1.</p>`
    }
];

export const researchData = [
    { 
        title: "1. Key Signs of Readiness", 
        icon: "clipboard-check",
        content: `<p>Age alone isn't the only factor. Before starting any solids (purées or BLW), your baby should meet <strong>all</strong> of these milestones, which typically happen around 6 months:</p><ul class="list-disc list-outside space-y-2 pl-5"><li><strong>Sits Independently:</strong> Baby can sit in a high chair unassisted or with minimal support and has good head and neck control. This is crucial for safely managing food and swallowing.</li><li><strong>Lost Tongue-Thrust Reflex:</strong> Baby no longer automatically pushes food out of their mouth with their tongue. You can test this by offering a (safe) empty spoon; if they push it out, they're likely not ready.</li><li><strong>Interest in Food:</strong> Baby watches you eat with interest, leans forward, and may try to grab food from your plate.</li><li><strong>Can Grab and Hold:</strong> Baby has developed the motor skills to pick up pieces of food and bring them to their mouth.</li></ul>`
    },
    {
        title: "2. Introducing Top Allergens",
        icon: "bean",
        content: `<p>Current guidelines have changed: experts now recommend introducing top allergenic foods <strong>early and often</strong> (after 6 months and once a few other foods have been tolerated) to help *prevent* allergies.</p><p>The top 9 allergens account for ~90% of food allergies:</p><ol class="list-decimal list-outside space-y-2 pl-5"><li>Cow's Milk (e.g., in yogurt, cheese)</li><li>Egg (fully cooked, e.g., scrambled or in a muffin)</li><li>Peanuts (NEVER whole. Offer as a thin paste on toast or watered down.)</li><li>Tree Nuts (e.g., almond, walnut. Offer as nut butter, same as peanuts.)</li><li>Fish (e.g., soft, flaky salmon)</li><li>Shellfish (e.g., minced shrimp)</li><li>Soy (e.g., tofu, edamame)</li><li>Wheat (e.g., toast, pasta)</li><li>Sesame (e.g., tahini swirled into yogurt)</li></ol><p><strong>SafetyProtocol:</strong> Introduce one allergen at a time. Wait 3-5 days before introducing another new allergen to watch for any reaction (hives, vomiting, swelling, wheezing). Once an allergen is successfully introduced, keep offering it regularly (e.g., 2-3 times a week) to maintain tolerance.</p>`
    },
    {
        title: "3. The Importance of Iron",
        icon: "beef",
        content: `<p>This is a common concern with BLW. At 6 months, a baby's natural iron stores (which they built up in the womb) begin to deplete. Breast milk is naturally low in iron. While formula and iron-fortified cereals are packed with it, BLW babies may not consume large quantities of cereal.</p><p>It is <strong>essential</strong> to offer iron-rich foods at every meal.</p><ul class="list-disc list-outside space-y-2 pl-5"><li><strong>Heme Iron (Easily Absorbed):</strong> Beef (slow-cooked strips, ground beef), chicken (dark meat), turkey (dark meat), salmon, sardines.</li><li><strong>Non-Heme Iron:</strong> Lentils, tofu, chickpeas, black beans, edamame, eggs, iron-fortified oatmeal/cereal (can be used in muffins or pancakes).</li></ul><p><strong>Pro-Tip:</strong> Pair non-heme iron foods with a food high in Vitamin C to dramatically boost absorption! (e.g., lentils with tomatoes, tofu with bell peppers, oatmeal with strawberries).</p>`
    },
    {
        title: "4. Reputable Sources",
        icon: "book-text",
        content: `<p>For more detailed information, you can look up guidelines from these trusted organizations:</p><ul class="list-disc list-outside space-y-2 pl-5"><li>American Academy of Pediatrics (AAP)</li><li>Centers for Disease Control and Prevention (CDC)</li><li>World Health Organization (WHO)</li><li>Solid Starts (A popular, comprehensive app and website)</li></ul>`
    }
];